services:
  db:
    container_name: app_db
    # restart: always
    image: postgres:latest
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5430:5432"
    env_file:
      - ./secrets/db/.env

  # frontend:

  backend:
    container_name: app_backend
    # restart: always
    depends_on:
      - db
    stdin_open: true
    tty: true
    ports:
      - "8200:8200"
    build:
      context: ./src/backend
      dockerfile: Dockerfile.dev
      args:
        HTTP_PORT: 8200
    develop:
      watch:
        - path: ./src/backend
          action: rebuild
    env_file:
      - ./secrets/backend/.env

  mail:
    container_name: app_mail
    image: mailhog/mailhog:latest
    # restart: always
    ports:
      - "1025:1025"
      - "8025:8025"

